### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by izme-mv** [dombold/MyHydroPi#1]
Greetings from the sunny side of life,
is there anyway can get a sql dump .
thanks

**Comment by dombold** [comment]
Hi
Not too sure what you mean by this, do you want an SQL dump of my current database tables?

**Comment by izme-mv** [comment]
Greetings from the sunny side of life Sorry about the late reply
Was waiting  for the reply but was somehow in the span folder

Yes would be great if you send me a dump of the sql
Thanks

**Comment by dombold** [comment]
Sorry I don't check back here as often as I should, the table dump is attached, I had to change it to a .txt file so that it would upload to github, you will need to convert it back to a .sql file in something like notepad++ to run it.

[hydropi_tables.txt](https://github.com/dombold/MyHydroPi/files/783141/hydropi_tables.txt)

 If you need more information let me know.

**Comment by izme-mv** [comment]
Thank you very much
Really helpful.
