### ISSUE TITLE
IDEA: add 2 temp sensors and flow meter to calc when pool is hot enough

### ISSUE THREAD

**Issue by boelle** [dombold/MyHydroPi#4]
i found this project as i wanted we live in a flat/appt and the pool is currently located at mominlaw accross town so need something to monitor it

one thing i plan to add to the pool is a solar heater that is the black rubber type that the water pumps through after the filter but before water re-enters the pool

it came to mind that if you monitor the temp before and after the solar heater and you know the flow rate there are formula's that can figure how much heat is added, and then i thought if you know the volume you can prob guess how long it would take to reach a temp you find good for a swim

would that be reasonble to add in the future?

**Comment by dombold** [comment]
Hi Boelle

It's probably not something that I am going to do personally as this was just a project I built for myself as a hobby and thought that I would share. As a suggestion, I would probably just add a couple more temp sensors to the Ordered Dictionary variables

("temp_1", {  # DS18B20 Temperature Sensor
                            "sensor_type": "1_wire_temp",
                            "name": "ds18b20_temp",
                            "is_connected": True,
                            "is_ref": False,
                            "ds18b20_file":
                            "/sys/bus/w1/devices/28-01157127dfff/w1_slave",
                            "accuracy": 1}),

and then use the temperature difference between them to control one of the relays with perhaps a "hard" start and stop time built in so that it's not running at night.

**Comment by boelle** [comment]
Hi

yep, and i just added a skimmer to the pool (its one of those with an inflate top ring, and the pump that comes with those do not have enough flowrate, so i will need another pump

the one with low flowrate can then be used for some solar mats and i just need to add detection when the sun is on them and start the 2nd pump when sun is there

the other stronger one should just run for the recommended 8 hours out of the 24 we got :-D

but lots of thinking needed

**Comment by boelle** [comment]
will close this one, but your code will sure be a starting point
